@echo off
echo Starting web server and making it PUBLIC...
echo Setting up tunnel for port 3000...
start cmd /k "npm start"
timeout /t 3 >nul
echo Generating public URL...
start cmd /k "npx localtunnel --port 3000"
echo Done! Please look at the new terminal window for your secure public URL (https://...).
